# Generated by Django 3.2.12 on 2022-03-24 13:40

import Core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rating_rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ИД')),
                ('star', models.PositiveSmallIntegerField(help_text="от 1 до 5. Соответствие: 1- 'Ненависть', 2 - 'Неприязнь', 3 - 'Нейтрально', 4 -'Обожание', 5 - 'Любовь'.  Возможно нулевое значение.", validators=[Core.validators.star_validator], verbose_name='Оценка пользователя')),
                ('evaluated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog_item', verbose_name='Оцениваемый (товар)')),
                ('evaluating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оценивающий (пользователь)')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'unique_together': {('evaluating', 'evaluated')},
            },
        ),
    ]
