# Generated by Django 3.2.12 on 2022-03-25 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.CharField(blank=True, choices=[('1', 'Ненависть'), ('2', 'Неприязнь'), ('3', 'Нейтрально'), ('4', 'Обожание'), ('5', 'Любовь')], default='5', help_text="от 1 до 5. Соответствие: 1- 'Ненависть', 2 - 'Неприязнь', 3 - 'Нейтрально', 4 -'Обожание', 5 - 'Любовь'", max_length=2, verbose_name='Оценка'),
        ),
    ]
