# Generated by Django 3.2.12 on 2022-03-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220325_2227'),
        ('rating', '0002_auto_20220325_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='catalog.item', verbose_name='Товар'),
        ),
    ]
