# Generated by Django 3.2.12 on 2022-03-24 13:40

import Core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalog_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ИД')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублековано')),
                ('slug', models.SlugField(help_text='Только цифры, буквы латиницы и символы - и _', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Название')),
                ('weight', models.PositiveSmallIntegerField(help_text='Больше 0, меньше 32767', verbose_name='Длинна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='catalog_tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ИД')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублековано')),
                ('slug', models.SlugField(help_text='Только цифры, буквы латиницы и символы - и _', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='catalog_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ИД')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублековано')),
                ('name', models.CharField(help_text='Макс 150 символов', max_length=150, verbose_name='Имя')),
                ('text', models.TextField(help_text='Минимум два слова. Обязательно содержится слово превосходно или роскошно', validators=[Core.validators.validate_brilliant, Core.validators.count_validator], verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog_category', verbose_name='Категория')),
                ('tegs', models.ManyToManyField(to='catalog.catalog_tag')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
